### PR TITLE
yaml for deployment of central fluentd collector with RBAC

### PR DESCRIPTION
**Pull request by leahnp**
I'm not sure why the yaml wasn't included in this repo prior to this, but here it is with RBAC added, mirrored in helm chart.

### CODE REVIEW

**Comment by coffeepac** [comment]
@mbachtel review this please

**Comment by notjames** [comment]
I've been taking a look at this. I'll be grokking K8s RBAC docs while going through this yaml. Mind if I hit you up on slack some time tomorrow to ask questions?

**Comment by leahnp** [comment]
@mbachtel or @notjames if it all looks good can one of you merge this?

**Comment by alejandroEsc** [comment]
LGTM

**Comment by notjames** [comment]
LGTM2, though I'm gonna be honest and say that I'm in the same boat with @mbachtel. However, based on what I have gleaned from documentation, this looks sane.

**Comment by mbachtel** [comment]
LGTM3

**Pull request merged**
